---
- hosts: all
  gather_facts: no
  become_method: sudo
  become: yes
  tasks:
    - name:  "Ensure custom fact directory exists"
      file:
        path=/etc/ansible/facts.d
        recurse=yes
        state=directory
    - name: "Install custom fact file"
      template:
        src: "{{ item }}"
        dest: /etc/ansible/facts.d/
        mode: 0755
      with_fileglob:
        - ./templates/*.fact
#        - ../templates/audit4/*.fact
#        - ../templates/audit5/*.fact
#        - ../templates/audit6/*.fact
    - name: reload ansible_local
      setup: filter=ansible_local
