---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: save all facts to host specific file
    copy:
      content: "{{ ansible_local | to_json }}\n"
      dest: "/root/samples/{{ansible_hostname}}.json"
    delegate_to: localhost
    
  - name: Add Hostname to Factfile
    shell: sed -i -e "s/^/{{ansible_nodename}}\|{{ansible_default_ipv4.address}}|/" /root/samples/{{ansible_hostname}}.json
    delegate_to: localhost
    
  - name: copy
    copy:
      remote_src: yes
      src: /root/samples/{{ansible_hostname}}.json
      dest: /var/lib/pgsql/test
      owner: postgres
      group: postgres
      mode: '0644'
    delegate_to: localhost

  - name: Create database
    postgresql_db:
      name: tamizhvaanan
    become_user: postgres
    delegate_to: localhost
    tags:
      - database
      
  - name: Create table
    postgresql_table:
      db: tamizhvaanan
      name: sample
      columns:
      - id SERIAL PRIMARY KEY
      - created_at TIMESTAMP DEFAULT NOW()
      - hostname VARCHAR(100)
      - ipaddress VARCHAR(100)
      - values JSON
    become_user: postgres
    delegate_to: localhost

  - name: test
    postgresql_query:
      db: tamizhvaanan
      query: COPY sample(hostname,ipaddress,values) from PROGRAM 'cat /var/lib/pgsql/test/*' delimiter '|'
    become_user: postgres
    delegate_to: localhost

#### SELECT id, created_at,hostname,ipaddress,values -> 'daytime2' AS values FROM sample;  -->> JSON query in db
#### \copy (SELECT created_at,ipaddress,values FROM dummy) TO '/var/lib/pgsql/myfile1.json';  -->> export as a file
#### \copy (select row_to_json(t) from(select * from dummy) t) to '/var/lib/pgsql/myfile.json'; -->> export in json file
#### select * from dummy where created_at = (select max(created_at) from dummy); -->> Select records based on last date
#### \copy (select row_to_json(t) from (select * from dummy where created_at = (select max(created_at) from dummy))t) to '/var/lib/pgsql/gody.json'; -->> export a file with last date in json format
#### SELECT id,created_at,hostname,ipaddress,values -> 'daytime2' AS values FROM dummy where id = 1; -->> calling a specified id with values
#### source /opt/rh/rh-postgresql10/enable -->> add path
#### su - postgres -c 'scl enable rh-postgresql10 -- psql'
#### scl enable rh-postgresql10 "psql -d tamizhvaanan -c \"select values->>'cramfs1' AS values from sample where id=5\"" -->> shell
